"use client";

import Gnb from "@/components/gnb";
import Header from "@/components/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { QueryClient, QueryClientProvider } from "react-query";
import { ReactQueryDevtools } from "react-query-devtools";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <ReactQueryDevtools />
          <div className="flex w-screen overflow-x-hidden font-base">
            <Gnb />
            <div className="flex-1">
              <Header />
              <div className="px-[45px] py-[45px] bg-[#f1f5f9] min-h-full">
                {children}
              </div>
            </div>
          </div>
        </QueryClientProvider>
      </body>
    </html>
  );
}
