"use client";

import Gnb from "@/components/gnb";
import Header from "@/components/header";
import type { Metadata } from "next";
import { QueryClient, QueryClientProvider } from "react-query";
import { ReactQueryDevtools } from "react-query-devtools";
import { RecoilRoot } from "recoil";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <body>
        <RecoilRoot>
          <QueryClientProvider client={queryClient}>
            <ReactQueryDevtools />
            <div className="flex w-screen overflow-x-hidden font-base">
              <Gnb />
              <div className="flex-1">
                <Header />
                <div className="px-[2.8125rem] py-[2.8125rem] bg-[#f1f5f9] min-h-full">
                  {children}
                </div>
              </div>
            </div>
          </QueryClientProvider>
        </RecoilRoot>
      </body>
    </html>
  );
}
